### ISSUE TITLE
Erreurs dans l'homogénéité des affichages

### ISSUE THREAD

**Issue by clenemce** [Veitzen/GL02_A23_LesCompilateursCosmiques_#10]
Lors de la communication à travers l'invite de commande, les commandes, les choix proposés à l'utilisateur, les retours à la ligne, la ponctuation, les majuscules, ne sont pas parfaitement homogènes.
Homogénéiser les écritures permettrait de rendre le logiciel plus professionnel. 
![Capture d'écran 2024-01-08 145917](https://github.com/Veitzen/GL02_A23_LesCompilateursCosmiques_/assets/105370561/4763b6f1-f7e0-4e86-a987-e92ef9b250e6)
![Capture d'écran 2024-01-08 150058](https://github.com/Veitzen/GL02_A23_LesCompilateursCosmiques_/assets/105370561/a0ea1812-1f08-4c33-a74b-5087ed60d74e)
![Capture d'écran 2024-01-08 150122](https://github.com/Veitzen/GL02_A23_LesCompilateursCosmiques_/assets/105370561/fbc4340e-7df6-47a6-bcb9-34a4b8678e92)
![Capture d'écran 2024-01-08 150327](https://github.com/Veitzen/GL02_A23_LesCompilateursCosmiques_/assets/105370561/4cbbd650-bd90-4ca6-8771-aa33fc0856bb)
![Capture d'écran 2024-01-08 150337](https://github.com/Veitzen/GL02_A23_LesCompilateursCosmiques_/assets/105370561/d2abed99-6c58-4589-9f0c-bd40ae29c9eb)

De plus, lorsqu'on sélectionne une commande, dans certains cas le menu d'accueil est coupé et on ne voit plus correctement l'historique des commandes.

**Comment by Dzi4dk** [comment]
Homogénéisation des divers print du programme pour les rendre plus propre.
Correction de diverses fautes d'orthographes.
Changement du tutoiement vers un vouvoiement lorsque l'on demande des informations à l'utilisateur.
![ticket3](https://github.com/Veitzen/GL02_A23_LesCompilateursCosmiques_/assets/147445740/3b5117f2-9ad4-40ed-b661-ac82378c9dab)
