### ISSUE TITLE
Fermeture interminable

### ISSUE THREAD

**Issue by clenemce** [Veitzen/GL02_A23_LesCompilateursCosmiques_#11]
Lorsqu'on quitte le programme par un autre moyen que par la commande '8 - Quitter le logiciel' la fermeture du logiciel semble infinie (par exemple lorsqu'on répond 'non' après qu'on nous ai demandé si on veux revenir à l'écran d'accueil), tandis qu'elle fonctionne correctement par la commande 8.
![Capture d'écran 2024-01-08 153348](https://github.com/Veitzen/GL02_A23_LesCompilateursCosmiques_/assets/105370561/b093872b-2d5d-4208-a352-3e557ea2a19e)
![Capture d'écran 2024-01-08 153558](https://github.com/Veitzen/GL02_A23_LesCompilateursCosmiques_/assets/105370561/7d675154-bd3f-4428-a45c-8fedc89b7c98)

**Comment by Dzi4dk** [comment]
Correction du problème en utilisant : return process.exit(1); pour terminer le programme plutôt que : break;
En effet, break ne fonctionne pas dans toutes les situations.
![Uploading ticket4.png…]()
