### ISSUE TITLE
Ecriture de la salle ou d'un cours en minuscule

### ISSUE THREAD

**Issue by clenemce** [Veitzen/GL02_A23_LesCompilateursCosmiques_#13]
Etant donnée que toutes les salles sont enregistrées en majuscule, il n'y a pas de confusion possible si l'utilisateur entre une salle en majuscule ou en majuscule. Cependant le programme ne lit pas le nom d'une salle entré en minuscule (s201 au lieu de S201).
On fait la même remarque pour le nom des cours. 

Il pourrait être intéressant que le programme soit capable de lire le nom des salles et des cours en minuscule au même titre qu'en majuscule. 
![Capture d'écran 2024-01-08 161459](https://github.com/Veitzen/GL02_A23_LesCompilateursCosmiques_/assets/105370561/dd9596c0-d752-4afd-898a-84369ddf2b66)
![Capture d'écran 2024-01-08 161643](https://github.com/Veitzen/GL02_A23_LesCompilateursCosmiques_/assets/105370561/b4b537e7-0826-480c-82f5-8b7fc42e170d)

**Comment by Dzi4dk** [comment]
Correction du problème de lecture en utilisant la fonction toLowerCase() dans le test de détection de l'entrée de l'utilisateur.
![ticket1](https://github.com/Veitzen/GL02_A23_LesCompilateursCosmiques_/assets/147445740/2f1c1adb-e250-437f-9db7-8170b51ffdfa)
![ticket2](https://github.com/Veitzen/GL02_A23_LesCompilateursCosmiques_/assets/147445740/936f462b-abdb-473a-91ff-1ca6e984dd3e)
