### ISSUE TITLE
Vérifier la liste des salles disponibles pour un créneau donné

### ISSUE THREAD

**Issue by Veitzen** [Veitzen/GL02_A23_LesCompilateursCosmiques_#2]
La fonctionnalité ne marche pas.
Erreur : 
TypeError: this.menuSalleLibrePourUnCreaneau is not a function
    at Main.afficherMenu (main.js:34:39)

**Comment by vignybrayan01** [comment]
Ajout de la fonction menuSalleLibrePourUnCreaneau() permettant d'afficher les salles disponibles pour un crénau donné
